language: cpp


jobs:
  include:
  
  - stage: "Check Style"
    name: "Check clang-format"
    os: linux
    addons:
        apt:
            packages:
                clang-6.0
                clang-format-6.0
                clang-tidy-6.0
    dist: xenial
    compiler: clang++-6.0
    script:
      - bash check_format.sh clang-format-6.0

  - stage: "Builds"
    name: "Linux Build"
    os: linux
    dist: xenial
    addons:
        apt:
            packages:
                clang-6.0
                clang-format-6.0
                clang-tidy-6.0
    compiler: clang++-6.0
    install:
      - sudo apt-get install autoconf automake libtool curl make g++ unzip
      - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protobuf-cpp-3.6.1.zip
      - unzip protobuf-cpp-3.6.1.zip
      - cd protobuf-cpp-3.6.1/protobuf-3.6.1
      - ./configure
      - make -j4
      - sudo make install
      - sudo ldconfig
      - CUDA_REPO_PKG=cuda-repo-ubuntu1604_10.0.130-1_amd64.deb
      - wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/$CUDA_REPO_PKG
      - sudo dpkg -i $CUDA_REPO_PKG
      - sudo apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub
      - rm $CUDA_REPO_PKG
      - sudo apt-get -y update
      - sudo apt-get install -y cuda
      - sudo ln -s /usr/local/cuda-10.0 /usr/local/cuda
      - git submodule update --init --recursive
      - cmake -D CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda -D CMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc -D CMAKE_CXX_COMPILER=clang++ .
    script: 
      - make -j4

notifications:
    email:
        on_success: never
